name: vitafit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: 1.1.0
  flutter_screenutil: ^5.1.1
  google_fonts: ^4.0.1
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.6
  card_swiper: ^3.0.1
  flutter_image_compress: ^1.1.0
  file_picker: ^4.2.0
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/images/other/
    - assets/images/coaches/
    - assets/images/forgot-password/
    - assets/images/mobile-payments/
    - assets/secure-login/
    - assets/tablet-login/
    - assets/images/home/
    - assets/images/all/
    - assets/images/brassiere/
    - assets/images/buttom/
    - assets/images/eating-disorder/
    - assets/images/healthy product/
    - assets/images/shoes/
    - assets/images/suite/
    - assets/images/top/
    - assets/images/sport materials/
    - assets/images/SALES DISCOUNT/
    - assets/icons/
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
